### ISSUE TITLE
Implementación de la seguridad al app

### ISSUE THREAD

**Issue by kevincarrenot** [JavierDuarteC/pruebas-node#12]
- [ ] Montar imagen UBUNTU 18 en aws, guardar la key 
- [ ] Grupo de seguridad con puertos 3000, 5000, 27017
- [ ] Instalar docker, docker compose
- [ ] Clonar repo desde la rama prueba-login
- [ ] Ejecutar build docker y up
- [ ] Probar que funcione el servicio
